### ISSUE TITLE
It keeps stuck on the ValueError: The stream has not the given quality error.

### ISSUE THREAD

**Issue by opensourcedept-simformsolutions** [adrz/twitch-realtime-handler#6]
Hello,
Based on your code, it seems that you have provided default values to the input arguments. However, your code keeps encountering the same exception, and I am unable to debug it any further. Could you please assist me with this issue? For your reference, I have used the img_grabber function.

    img_grabber = TwitchImageGrabber(
        twitch_url="https://www.twitch.tv/danucd",
        quality="480p",
        blocking=True,
        rate=10
        )

**Comment by adrz** [comment]
What is the error?

**Comment by opensourcedept-simformsolutions** [comment]
raise ValueError("The stream has not the given quality")
ValueError: The stream has not the given quality

I am running it on ubuntu 20.04 with requirement-example data as per mentioned in the readme file.

**Comment by opensourcedept-simformsolutions** [comment]
@adrz  I have resolved the above issue but what is happening now is the stream is getting started and all the dialogs before the stream are running but after that, the readable frame is just blank. So, I am not able to understand why the data is not coming. Do we have to perform a login beforehand or any other thing?

Please guide me here as I need your support to understand it better.

**Comment by adrz** [comment]
@opensourcedept-simformsolutions the other day your streamer was using an unusual quality (it was 480p30). So the quality 480p didn't exist at that time. I'll do a fix for that.

However, today the stream has 480p quality... I'm currently running:

`python realtime-face-detection.py --twitch-url https://www.twitch.tv/danucd --fps 10`

and it works as expected. Could you try to run this script and see if you get an error or something?

**Comment by adrz** [comment]
also just release the fix:

`pip install --upgrade twitchrealtimehandler`
