### ISSUE TITLE
Please add licensing information

### ISSUE THREAD

**Issue by jh0ker** [adrz/twitch-realtime-handler#8]
Hello, 

This module is perfect for a project that I am working on. However, I noticed it doesn't contain any licensing information, which makes it legally risky to use. I'd greatly appreciate if you could add a license! 

If you are in doubt about which license to choose, you can check out https://choosealicense.com/ or similar websites to help you choose.

Best wishes,
Jannes

**Comment by adrz** [comment]
Thank you @jh0ker i think MIT is perfect for this kind of project https://github.com/adrz/twitch-realtime-handler/pull/9 
Is it good for you ?

**Comment by jh0ker** [comment]
Hey, sorry for the late response, I seem to have missed your response. 
The MIT license is very permissive which is great for adoption, so it's perfect for my needs. 
I appreciate you taking the time and making this project available, it's really useful!
